In [ ]:
inp = input()
proverb = inp.lower()[:-1].split(' ')
last = inp.lower()[-1]
for ind, word in enumerate(proverb):
  if len(word) > 1:
    n = 0
    new_word = ''
    while n != min(len(word[::2]), len(word[1::2])):
      new_word += word[1::2][n] + word[::2][n]
      n += 1

    if len(word) % 2 != 0:
      new_word += word[::2][n]
    else:
      pass
  
    proverb[ind] = new_word

print(' '.join(proverb).capitalize()+last)

Программисты - это устройства, преобразующие кофеин в код.
Рпгоарммсиыт - тэо суртйотсав, рпоербзаюуище окефни в окд.

In [ ]:
import pandas as pd

db = pd.read_csv('/content/drive/MyDrive/AI-ACADEMY/StudentsPerformance.csv')
db

,gender,faculty,parental level of education,lunch,test preparation course,charms score,potions score,dark arts score
0,female,faculty B,Koldovstoretz,standard,none,72,72,74
1,female,faculty C,Durmstrang Institute,standard,completed,69,90,88
2,female,faculty B,Hogwarts School of Witchcraft and Wizardry,standard,none,90,95,93
3,male,faculty A,Beauxbatons Academy of Magic,free/reduced,none,47,57,44
4,male,faculty C,Durmstrang Institute,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,faculty E,Hogwarts School of Witchcraft and Wizardry,standard,completed,88,99,95
996,male,faculty C,Mahoutokoro School of Magic,free/reduced,none,62,55,55
997,female,faculty C,Mahoutokoro School of Magic,free/reduced,completed,59,71,65
998,female,faculty D,Durmstrang Institute,standard,completed,68,78,77
999,female,faculty D,Durmstrang Institute,free/reduced,none,77,86,86

In [ ]:
import math
db['charms score'][db['charms score'] <= db['charms score'].mean()].count()

In [ ]:
import math
numb = input()
cmd = input()

F = True
f = 10 ** 11

def check(numb):
    try:
        float(numb)
        return True
    except ValueError:
        return False
        

if check(numb):
    numb = float(numb)
    if float(numb) % 1 == 0:
        numb = int(numb)
else:
    print('None')
    F = False

def square(a):
  return (math.trunc((a**2) * f) / f)

def cube(a):
  return (math.trunc((a**3) * f) / f)

def si(a):
  return (math.trunc(math.sin(math.radians(a)) * f) / f)

def co(a):
  return (math.trunc(math.cos(a) * f) / f)

def absolute(a):
  return (math.trunc(abs(a) * f) / f)

if F:
    if cmd == 'Квадрат числа' and check(square(numb)):
      print(square(numb))
    elif cmd == 'Куб числа' and check(cube(numb)):
      print(cube(numb))
    elif cmd == 'Синус числа' and check(si(numb)):
      print(si(numb))
    elif cmd == 'Косинус числа' and check(co(numb)):
      print(co(numb))
    elif cmd == 'Модуль числа' and check(absolute(numb)):
      print(absolute(numb))
    else:
      print('None')

5
Квадрат числа
25.0

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/AI-ACADEMY/football.csv')
df

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,13121,J. Lundstram,19,England,Crewe Alexandra,1100000,1000,CM,34,38,...,43,45,40,48,47,10,13,7,8,9
12893,13122,N. Christoffersson,19,Sweden,Trelleborgs FF,60000,1000,ST,23,52,...,43,42,22,15,19,10,9,9,5,12
12894,13123,B. Worman,16,England,Cambridge United,60000,1000,ST,25,40,...,55,41,32,13,11,6,5,10,6,13
12895,13124,D. Walker-Rice,17,England,Tranmere Rovers,60000,1000,RW,44,50,...,50,46,20,25,27,14,6,14,8,9
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9

In [3]:
df.Position.nunique()

27

In [4]:
df.Name.value_counts()

J. Rodríguez    9
J. Hernández    6
L. López        5
J. Williams     5
R. Williams     5
               ..
R. Teibert      1
A. Nübel        1
Z. Al Sahafi    1
J. Schouten     1
G. Nugent       1
Name: Name, Length: 12326, dtype: int64

In [5]:
df.Wage.min()

1000

In [6]:
df.tail(1)

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9

In [7]:
from statistics import mean
round(mean([df.GKDiving.mean(),
df.GKHandling.mean(),
df.GKKicking.mean(),
df.GKPositioning.mean(),
df.GKReflexes.mean()]))
df.mean()[-5:]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  import sys

GKDiving         17.218345
GKHandling       16.962317
GKKicking        16.797938
GKPositioning    16.950221
GKReflexes       17.315965
dtype: float64

In [8]:
df[df.Club == "Manchester United"].Nationality.nunique()

13

In [11]:
df.Value.value_counts(bins=6).sort_values()

(98750000.0, 118500000.0]        3
(79000000.0, 98750000.0]         7
(59250000.0, 79000000.0]        32
(39500000.0, 59250000.0]        48
(19750000.0, 39500000.0]       181
(-118500.001, 19750000.0]    12626
Name: Value, dtype: int64